# Generated by Django 4.2.6 on 2023-10-06 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='check_out_time',
        ),
    ]
