# Generated by Django 4.2.6 on 2023-10-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='tec_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
