# Generated by Django 4.2.6 on 2023-10-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_person_tec_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.IntegerField(max_length=20)),
                ('camera_url', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('camera_name', models.CharField(max_length=500)),
                ('camera_location', models.CharField(max_length=500)),
            ],
        ),
    ]
