# Generated by Django 4.2.6 on 2023-10-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='camera_id',
            field=models.IntegerField(),
        ),
    ]
