# Generated by Django 4.2.6 on 2023-10-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_camera_camera_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='camera_location',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='camera_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='password',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
