# Generated by Django 4.2.6 on 2023-10-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_camera_camera_id_alter_camera_camera_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='camera_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
