# Generated by Django 4.2.6 on 2023-11-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_camera_camera_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='status',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
