# Generated by Django 4.2.6 on 2023-11-02 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_camera_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='status',
            new_name='camera_status',
        ),
    ]
